---

- include: local_hostnames.yml
  when: local_hostnames is defined

- include: local_ssl.yml
  when: local_ssl is defined

- name: add Entr'ouvert apt key
  apt_key: url=https://deb.entrouvert.org/entrouvert.gpg id=2CCFEC25

- name: add required repositories
  apt_repository: repo="{{ item }}" update_cache=yes
  with_items: "{{ required_repositories }}"

- name: install required packages
  apt: name="{{ item }}" update_cache=yes
  with_items: "{{ required_packages }}"

- include: postgresql.yml
  become_user: postgres
- include: hobo.yml
- include: authentic.yml
- include: combo.yml
- include: wcs.yml
- include: passerelle.yml
- include: publik.yml